FROM node:hydrogen-slim AS base

RUN corepack enable
COPY package.json pnpm-lock.yaml /frontend/
WORKDIR /frontend/
RUN pnpm install --frozen-lockfile

FROM base as build

COPY . /frontend/
RUN pnpm build

CMD ["pnpm", "start"]
