services:
  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    command: npm run dev
    volumes:
      - ./frontend:/frontend
      - node_modules:/frontend/node_modules

volumes:
  node_modules:
