FROM python:3.12-slim

WORKDIR /backend

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONIOENCODING=UTF-8 \
    SHELL=/bin/sh \
    LANG=en_US.UTF-8

COPY . .

RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    build-essential \
    libpq-dev \
    python3-dev

RUN pip install poetry && \
    poetry install --no-ansi --no-interaction

ENV PATH="/backend/.venv/bin:$PATH"
