FROM python:3.12-slim

WORKDIR /backend

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONIOENCODING=UTF-8 \
    SHELL=/bin/sh \
    LANG=en_US.UTF-8

COPY . .

RUN pip install poetry && \
    poetry install --no-ansi --no-interaction

ENV PATH="/backend/.venv/bin:$PATH"
