FROM python:3.12-slim

WORKDIR /backend

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=true

COPY . .

RUN pip install poetry && \
    poetry install --no-ansi --no-interaction

ENV PATH="/backend/.venv/bin:$PATH"
