name: frontend

on:
  push:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    working-directory: ./frontend
    shell: bash

env:
  TEST_IMAGE: ${{ secrets.ACR_REGISTRY }}/frontend:test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          pull: true
          load: true
          target: base
          tags: ${{ env.TEST_IMAGE }}
          context: ./frontend
