name: "frontend"

on:
  push:
    branches: ["main"]
    paths:
      - "./frontend/**"

defaults:
  run:
    working-directory: "./frontend"
    shell: "sh"

env:
  BASE_IMAGE: "${{ secrets.ACR_REGISTRY }}/frontend"
  TEST_IMAGE: "${{ env.BASE_IMAGE }}:test"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"

      - name: "docker"
        uses: docker/setup-buildx-action@v3

      - name: "registry"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ secrets.ACR_REGISTRY }}"
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: "build"
        uses: "docker/build-push-action@v5"
        with:
          push: true
          pull: true
          target: "base"
          tags: "${{ env.TEST_IMAGE }}"
          context: "./frontend"
