name: "frontend"

on:
  push:
    branches: ["main"]
    paths:
      - "./frontend/**"

defaults:
  run:
    working-directory: "./frontend"
    shell: "sh"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v4"

      - uses: "pnpm/action-setup@v3"
        with:
          version: "8"

      - uses: "actions/setup-node@v4"
        with:
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"
          node-version-file: "./frontend/.nvmrc"

      - run: "pnpm install"
