name: "frontend"

on:
  push:
    branches:
      - "main"
    paths:
      - "frontend/**/*.c?jsx?"
      - "frontend/**/*.c?tsx?"
      - "frontend/**/*.json"
      - "frontend/**/*.css"
  workflow_dispatch:

defaults:
  run:
    working-directory: "./frontend"
    shell: "bash"

env:
  TEST_IMAGE: "${{ secrets.ACR_REGISTRY }}/frontend:test"
  PROD_IMAGE: "${{ secrets.ACR_REGISTRY }}/frontend:prod"

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"

jobs:
  deploy:
    runs-on: "ubuntu-latest"
    steps:
      - name: "checkout"
        uses: "actions/checkout@v4"

      - name: "qemu"
        uses: "docker/setup-qemu-action@v3"

      - name: "buildx"
        uses: "docker/setup-buildx-action@v3"

      - name: "registry"
        uses: "docker/login-action@v3"
        with:
          registry: "${{ secrets.ACR_REGISTRY }}"
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: "build"
        uses: "docker/build-push-action@v5"
        with:
          push: false
          pull: false
          load: true
          target: "base"
          tags: "${{ env.TEST_IMAGE }}"
          context: "./frontend"

      - name: "lint"
        run: "docker run --rm ${{ env.TEST_IMAGE }} npm run lint"

      - name: "release"
        uses: "docker/build-push-action@v5"
        with:
          push: true
          pull: true
          load: true
          target: "build"
          tags: "${{ env.PROD_IMAGE }}"
          context: "./frontend"
